server:
  port: 8080
spring:
  # Configuración de la conexión a la base de datos PostgreSQL
  datasource:
    url: jdbc:postgresql://postgres_test:5432/test
    username: postgres
    password: contrasena

  # Configuración de JPA y Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:

      ddl-auto: create-drop