insert into persons (name, city) values ('Glen Hobbema', 'Cigedang');
insert into persons (name, city) values ('Wendie Breedy', 'Vrede');
insert into persons (name, city) values ('Beverley Peckham', 'Kabasalan');
insert into persons (name, city) values ('Dniren Meneghi', 'Lālmohan');
insert into persons (name, city) values ('Rudd Lesurf', 'Pégeia');
insert into persons (name, city) values ('Deni Grassi', 'Vale de Figueira');
insert into persons (name, city) values ('Lishe Chuney', 'Balingoan');
insert into persons (name, city) values ('Orelia Caulwell', 'Titab');
insert into persons (name, city) values ('Jamima Bearn', 'San Francisco');
insert into persons (name, city) values ('Carolee Durdan', 'Jifnā');
insert into persons (name, city) values ('Arley Snepp', 'Now Zād');
insert into persons (name, city) values ('Codi Cranny', 'Danchang');
insert into persons (name, city) values ('Margit Scholard', 'Šuto Orizare');
insert into persons (name, city) values ('Arne Eastman', 'Oklahoma City');
insert into persons (name, city) values ('Elnora Lauchlan', 'Pueai Noi');
insert into persons (name, city) values ('Thom Sweynson', 'Rochester');
insert into persons (name, city) values ('Bertie Pygott', 'Qozonketkan');
insert into persons (name, city) values ('Demetre Riply', 'Nīshābūr');
insert into persons (name, city) values ('Enrica Maysor', 'Tillabéri');
insert into persons (name, city) values ('Ronny Palfery', 'Gardanne');
insert into persons (name, city) values ('Cozmo Iozefovich', 'Bombardopolis');
insert into persons (name, city) values ('Mikel Ilott', 'Santiago de Baney');
insert into persons (name, city) values ('Sully Hirthe', 'Valence');
insert into persons (name, city) values ('Isidora Keirl', 'Wenwuba');
insert into persons (name, city) values ('Devora Hawkins', 'Baddomalhi');
insert into persons (name, city) values ('Newton Dunstall', 'Dún Laoghaire');
insert into persons (name, city) values ('Lev Woollard', 'Vejprnice');
insert into persons (name, city) values ('Olwen Beddoe', 'Heping');
insert into persons (name, city) values ('Kylynn Nevet', 'Wuyang');
insert into persons (name, city) values ('Tobias Longstaffe', 'Banjar Buahan');
insert into persons (name, city) values ('Augustine Pierson', 'Krasnomayskiy');
insert into persons (name, city) values ('Riannon Dibsdale', 'Ostružnica');
insert into persons (name, city) values ('Mario Matsell', 'Nerchinsk');
insert into persons (name, city) values ('Silvain Peterkin', 'Liboran');
insert into persons (name, city) values ('Aigneis Menhci', 'Władysławowo');
insert into persons (name, city) values ('Ainsley Novotne', 'Jindřichův Hradec');
insert into persons (name, city) values ('Aurelea Linneman', 'Budapest');
insert into persons (name, city) values ('Anastasie Harget', 'Dongfeng');
insert into persons (name, city) values ('Kippie Verman', 'Liuji');
insert into persons (name, city) values ('Lora Holdey', 'Mambulo');
insert into persons (name, city) values ('Veradis todor', 'Dan Khun Thot');
insert into persons (name, city) values ('Selle Troop', 'Shakhtars’k');
insert into persons (name, city) values ('Emelen Quinane', 'San Juan Opico');
insert into persons (name, city) values ('Immanuel Couvert', 'Cercal');
insert into persons (name, city) values ('Lil Cowie', 'Ciroyom');
insert into persons (name, city) values ('Aubree Porcher', 'Khārān');
insert into persons (name, city) values ('Honey Espin', 'Chojnice');
insert into persons (name, city) values ('Rani Yakunin', 'Vanáton');
insert into persons (name, city) values ('Daffi Basilotta', 'Baoxia');
insert into persons (name, city) values ('Harald Audenis', 'Jiangkou');
insert into persons (name, city) values ('Raffaello Pisco', 'Erdaobaihe');
insert into persons (name, city) values ('Shoshanna Walduck', 'Misheronskiy');
insert into persons (name, city) values ('Dari Fache', 'Komorní Lhotka');
insert into persons (name, city) values ('Barnie Keppel', 'Andongrejo');
insert into persons (name, city) values ('Fancie Surby', 'Garhi Yāsīn');
insert into persons (name, city) values ('Austine Folkes', 'Dihtyari');
insert into persons (name, city) values ('Nichole Barker', 'Kout na Šumavě');
insert into persons (name, city) values ('Mannie Farlham', 'Kebloran');
insert into persons (name, city) values ('Marijn Feldharker', 'Shiqiao');
insert into persons (name, city) values ('Zachary Stirley', 'Būrewāla');
insert into persons (name, city) values ('Saunders Sim', 'Indralayang');
insert into persons (name, city) values ('Gerrard Tillman', 'Velventós');
insert into persons (name, city) values ('Normy Jenner', 'Looc');
insert into persons (name, city) values ('Maris Meo', 'Luoyuan');
insert into persons (name, city) values ('Teodora Gubbin', 'Touguinha');
insert into persons (name, city) values ('Austina Deer', 'Rebe');
insert into persons (name, city) values ('Suzann Tatham', 'Sukabatu');
insert into persons (name, city) values ('Benoite Korlat', 'Xiaochengzi');
insert into persons (name, city) values ('Sid Sivess', 'Laolong');
insert into persons (name, city) values ('Hamil Dowbiggin', 'Changling');
insert into persons (name, city) values ('Sharla Ells', 'Lepaterique');
insert into persons (name, city) values ('Jerrilyn Oppie', 'Taipingzhuang');
insert into persons (name, city) values ('Tades Januszkiewicz', 'São Tomé');
insert into persons (name, city) values ('Valentine Teaze', 'Kinsale');
insert into persons (name, city) values ('Ralf Carmen', 'Mashava');
insert into persons (name, city) values ('Iris Fero', 'Rakvere');
insert into persons (name, city) values ('Forbes Rosentholer', 'Eloy Alfaro');
insert into persons (name, city) values ('Anatol Foye', 'Tchamba');
insert into persons (name, city) values ('Con Leaman', 'Luodian');
insert into persons (name, city) values ('Maryellen Rockcliffe', 'Divisoria');
insert into persons (name, city) values ('Den Alfonso', 'Dŭstí');
insert into persons (name, city) values ('Cad Grimshaw', 'Butajīra');
insert into persons (name, city) values ('Nannette Bengtson', 'Buga');
insert into persons (name, city) values ('Moshe Cassidy', 'Kaltan');
insert into persons (name, city) values ('Desmund Benneyworth', 'Liulin');
insert into persons (name, city) values ('Isidor Brewin', 'Limoeiro do Norte');
insert into persons (name, city) values ('Flossi Cowin', 'Karanganyar');
insert into persons (name, city) values ('Leupold Steffans', 'Pasirtujuhpuluh');
insert into persons (name, city) values ('Robina Paulitschke', 'Brea Pozo');
insert into persons (name, city) values ('Evered Rickardsson', 'Voinjama');
insert into persons (name, city) values ('Alister Dunnan', 'Wum');
insert into persons (name, city) values ('Doloritas Gartsyde', 'Sutukung');
insert into persons (name, city) values ('Linet Antognazzi', 'Comagascas');
insert into persons (name, city) values ('Birk Park', 'Piñahan');
insert into persons (name, city) values ('Zarah Ryal', 'Huajialing');
insert into persons (name, city) values ('Keelby Pickup', 'Postřekov');
insert into persons (name, city) values ('Eb Ewells', 'Maodian');
insert into persons (name, city) values ('Winn Steels', 'Emiliano Zapata');
insert into persons (name, city) values ('Avril Dunnett', 'Futuroscope');
insert into persons (name, city) values ('Philipa Di Claudio', 'Oslo');
